k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: aleix.abengochea-fdc-eu-prelive
  currentCluster: fdc-eu-prelive
  clusters:
    acdc-ppe-eu-live:
      namespace:
        active: ppe-traffic-ingest
        lockFavorites: false
        favorites:
        - all
        - ppe-traffic-ingest
        - default
      view:
        active: deployment
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    fdc-eu-dev:
      namespace:
        active: ppe-lhi
        lockFavorites: false
        favorites:
        - ppe-lhi
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    fdc-eu-live:
      namespace:
        active: platform-normalizer
        lockFavorites: false
        favorites:
        - platform-normalizer
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    fdc-eu-prelive:
      namespace:
        active: analytics
        lockFavorites: false
        favorites:
        - analytics
        - platform-normalizer
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    minikube:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/4l/3bl27lwd1bxb4520qlgbc9qm0000gp/T/k9s-screens-aleixabengochea
